CREATE DATABASE TutorialDB2;
USE TutorialDB2;

CREATE TABLE Persons(
id INT PRIMARY KEY,
Name VARCHAR(20),
)

INSERT INTO Persons VALUES
(1,'AJAY'),
(2,'VIJAY'),
(3,'ROHAN'),
(4,'ADITYA');

SELECT * from Persons
ORDER BY ID DESC;


--USING ANY AND ALL
SELECT ProductName
FROM Products
WHERE ProductID = ANY
  (SELECT ProductID
  FROM OrderDetails
  WHERE Quantity > 99);


  --CREATING VIEWS
  CREATE VIEW My_view as 
  Select * FROM Persons;


SELECT * FROM MY_VIEW;
uPDATE MY_VIEW 
SET Name = 'Modi'
where id = 1;
  --SQL SERVER FUNCTIONS
  --CONCAT
  SELECT CONCAT('Sir', ' ', NAME) as name FROM Persons;

  --leN RETURNS THE LENGTH OF THE STRING
SELECT LEN('HIPPOPOTAMAUS');


--REVERSE	Reverses a string and returns the result
SELECT REVERSE('HIPPOPOTAMAUS');
GO;

--STORED PROCEDURES
CREATE PROCEDURE SelectAllCustomers @City nvarchar(30)
AS
SELECT * FROM Customers WHERE City = @City
GO;
--WE CAN USE SELECTALLCUSTOMERS @CITY = 'LONDON' 


SELECT * FROM PERSONS;
ALTER TABLE PERSONS
ALTER COLUMN Name VARCHAR(10);
INSERT INTO PERSONS VALUES(5,'PONGILIPOQRSTU');







